dir = Pathname(__FILE__).dirname.expand_path / 'support'

require dir / 'array'
require dir / 'errors'
require dir / 'hook'
require dir / 'kernel'
require dir / 'logger'
require dir / 'module'
require dir / 'naming_conventions'
require dir / 'symbol'
