#
#  datamapper.org is build with webby 0.4.0
#
#  sudo gem install webby -v0.4.0
#

require 'webby'
load 'tasks/setup.rb'

task :default => :build

desc 'depoloy the site to the webserver'
task :deploy => [:build, 'deploy:rsync']

# EOF
